config/routes.rb
LabControl::Application.routes.draw do
  resources :raports
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :sensors

  root :to => 'pages#home'

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
end

app/models/raport.rb
# == Schema Information
#
# Table name: raports
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  body       :string(255)
#

class Raport < ActiveRecord::Base
   attr_accessible :body, :user_id
   belongs_to :user
   #default_scope :order => 'raports.created_at DESC'

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :sensor_name, :value
  validates_presence_of :sensor_name, :value

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  name            :string(255)
#  ROM             :string(255)
#  password_digest :string(255)
#  email           :string(255)
#  cardN           :string(255)
#

class User < ActiveRecord::Base
   attr_accessible :name, :email, :cardN, :ROM, :password, :password_confirmation
   has_many :raports, :dependent => :destroy

   validates :ROM, :presence => true, :uniqueness => true
                                        
   has_secure_password                  
                                        
   validates_presence_of :password      

  def self.find_or_create_by_ROM (rom)
    first(:conditions => {:ROM => rom}) || create!(:ROM => rom, :password => '1', :password_confirmation => '1') 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private
         
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end       
             
  def login_required                                              
    unless current_user                                           
      flash[:info] = "Please input your login and password first."
      redirect_to signin_path                                     
    end                                                           
  end

  helper_method :current_user

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      redirect_to(user_path(current_user))
    end
    @title = "Home"
  end
end

app/controllers/raports_controller.rb
class RaportsController < ApplicationController
  before_filter :login_required, :only => [:index, :show, :destroy]
  respond_to :html, :xml, :json, :js

  def index
    #@raports = Raport.all
    #@raports = Raport.paginate(:page => params[:raport_page], :per_page => 10 )
    @sensorL = Sensor.find(:last, :conditions => {:sensor_name => 'Light'})
    @sensorT = Sensor.find(:last, :conditions => {:sensor_name => 'Temperature'})
    #@new_raports = Raport.where("created_at > ?", Time.at(params[:after].to_i + 1)).paginate(:page => params[:raport_page], :per_page => 10 )
    @raports = Raport.where("created_at > ?", Time.at(params[:after].to_i + 1)).paginate(:page => params[:raport_page], :per_page => 10)
  end

  def show
    @raport = Raport.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @raport }
    end
  end

  def create
    @raport = Raport.new(params[:raport])
    @ROM = params[:raport].delete(:body)
    @user = User.find_or_create_by_ROM @ROM
    @raport.user_id = @user.id
    respond_to do |format|
      if @raport.save
        format.html {redirect_to(users_path)}
      end
    end
  end

  def destroy
    @raport = Raport.find(params[:id])
    @raport.destroy

    respond_to do |format|
      format.html { redirect_to raports_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  def create
    @sensor = Sensor.new()
    @sensor.value = params[:data][:TemperatureWallrouter]
    @sensor.sensor_name = 'Temperature'
    @sensor2 = Sensor.new()
    @sensor2.value = params[:data][:LightWallrouter]
    @sensor2.sensor_name = 'Light'
      if @sensor.save && @sensor2.save
        render :text => '', :status => 200
      end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Log in."
      redirect_to reports_path
    else
      flash[:error] = "Invalid email or password"
      @title = "Sign in"
      render "new"
    end
  end  
 
  def destroy
   session[:user_id] = nil
   redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :only => [:index, :edit, :update, :show, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create                                                
    @user = User.new(params[:user])                         
    if @user.save                                           
      flash[:success] = "Welcome to the Laboratory Control System"
      session[:user_id] = @user.id                          
      redirect_to @user                                     
    else                                                    
      @title = "Sign up"                                    
      render 'new'                                          
    end                                                     
  end                                                       

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def title
    base_title = "Laboratory Control System"
      if @title.nil?
        base_title
      else
        "#{base_title} | #{@title}"
      end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/raports_helper.rb
module RaportsHelper
end

app/helpers/sensor_helper.rb
module SensorHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation", class='alert alert-error'>
    <h2><%= pluralize(object.errors.count, "error") %>
    prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
    from being saved:</h2> 
    <p>There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>                                                      

app/views/layouts/_header.html.erb
<header>
  <div class = "navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "LABORATORY CONTROL SYSTEM", raports_path, :class => 'brand' %>
        <ul class="nav pull-right">
          <li><%= link_to "Home", raports_path %></li>
          <% if current_user %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Sign out", signout_path %>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'bootstrap/css/bootstrap.css'%>
<%= stylesheet_link_tag 'bootstrap/css/bootstrap-responsive.css' %>
<%= stylesheet_link_tag 'custom' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= render "layouts/stylesheets" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "bootstrap-dropdown" %>
    <%= javascript_include_tag "bootstrap-alert" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class = "container">
      <%= render "layouts/header" %>
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= value %>
          </div>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Welcome to Laboratory Control System<h2>
<%= link_to "SIGN UP NOW", signup_path , :class => 'btn btn-danger' %>

app/views/raports/_climate.html.erb
<%= @sensorL.sensor_name %> : <%= @sensorL.value %> <br/>
<%= @sensorT.sensor_name %> : <%= @sensorT.value %>

app/views/raports/_raport.html.erb
<tr class="raport" data-time="<%= raport.created_at.to_i %>">
  <td>
    <% if raport.body == "BUTTON" %>
      <i class= "icon-arrow-left"></i>
    <% else %>
      <i class= "icon-arrow-right"></i>
    <% end %>
    <%= raport.body %>
  </td>
  <td>
    <%= raport.created_at %>
  </td>
</tr>

app/views/raports/index.html.erb
<div class="row">
  <div class="span4 offset4">
<table class="table" id="raports" >
      <thead>
        <tr>
          <th>Raport body</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        <%= render @raports %>
        <%= will_paginate @raports, :param_name => 'raport_page', :renderer => BootstrapPagination::Rails %>
      </tbody>  
    </table>
  </div>  
  <div class="span2 offset2" id="climate" >
    <%= render "climate" %>
  </div>

app/views/raports/index.js.erb
$('#raports').append("<%= escape_javascript(raw render(@raports))%>");
$('#climate').html("<%= escape_javascript(render(:partial => "climate"))%>");

app/views/users/edit.html.erb
<h2>Edit user</h2>

<%= form_for (@user) do |f| %>
  <%= render 'layouts/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cardN %>
    <%= f.text_field :cardN %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="submit">
    <%= f.submit "Update", :class => 'btn btn-primary' %>
  </div>
<% end %> 

app/views/users/index.html.erb
<div class="row">
  <div class="span4">
    <table class="table">
      <thead>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
      </thead>
      <tbody>
<% @users.each do |user| %>
  <tr>
    <td><%= user.ROM %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/users/show.html.erb
<h4>User name: <%= @user.name %></h4>
<div class="row">
  <div class="span4">
    <table class="table">
      <tbody>  
        <% @user.raports.each do |raport| %>
          <tr>
            <td><%= raport.body %></td>
            <td><%= raport.created_at %></td>
          </tr>
        <% end %>
      </tbody>  
</table>        